name: dialog_flow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  dialogflow_grpc: ^0.2.9
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  sound_stream: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/credentials.json
